### ISSUE TITLE
Many Canon Names (Suggestion)

### ISSUE THREAD

**Issue by MadsInZero** [DeathChaos25/PQ2_MC_Name_Patch#1]
Since each protagonist usually has a couple of names that people prefer, and no two fans would agree on the exact same names for four protagonists, would it be possible to create a launcher that generates the files based on user input?

Ideally, text entry (using smaller characters for the entered names so they can have a longer length without breaking the game's formatting), or at least a toggle between two options for each character (Ren VS Akira, Kotone VS Minako, Makoto VS Minato, Yu VS Souji).

I don't know how feasible this would be, so if it's too difficult to implement the patch as it stands is already pretty darn amazing, but this could turn it into something even more so.

**Comment by HoneyOTU1337** [comment]
personally i would like to have
Minato Arisato
Minako Arisato
Yu Narukami
Akira Kurusu

**Comment by DeathChaos25** [comment]
Sadly the way this patch works is a bit complicated to automate, due to the fact that new custom code is being injected and the game's exheader is being adjusted to accommodate for this, so the only real way to change names easily would be for the end user to take the source code for the assembly patches here and build them themselves.

Only way I could think of would be something funky like making a code.bin with default long strings that the end user can easily hex edit their names into, would be the only easily doable way with my current experience.

**Comment by MadsInZero** [comment]
If that funky solution could work, would it be possible to make a program that converts user input into hex and inserts them at the right places? Or is it a case of everything being too interdependent?

Either way, thank you for both the reply and the patch itself.

**Comment by DeathChaos25** [comment]
Check latest release, this is the current solution I can provide to the best of my abilities (at the moment), this issue will be re-opened later if a better method happens
