### ISSUE TITLE
Mod Compendium Compatibility?

### ISSUE THREAD

**Issue by DannyB5544** [DeathChaos25/PQ2_MC_Name_Patch#2]
As in the title, I'm curious: does the mod support being combined in [The Mod Compendium](https://amicitia.github.io/guides/p5/mod-compendium)?

**Comment by DeathChaos25** [comment]
Mod Compendium is not done by me, but there should be no problem with using CPKs built using mod compendium.

**Comment by DannyB5544** [comment]
so just slap the non-cpk built files into Luma?

**Comment by DeathChaos25** [comment]
No, you need to build a cpk with the files, read the description, it says it supports mod.cpk, meaning you'd build a cpk with modded files and name it mod.cpk

**Comment by DeathChaos25** [comment]
Due to people not reading the release notes, I've moved the latest release containing the mod.cpk patch to a different repository, the mod support patch also clearly stated that it was a mod.cpk support, not just loose files, that'd take way more reprogramming.

https://github.com/DeathChaos25/PQ2_MOD_CPK_NAMES/releases/tag/v1.0

**Comment by DannyB5544** [comment]
Ah. My bad, mobile is horrendous at showing the releases and I was looking at this at the train station. Thanks anyway, and when I do get home I'll actually build it in Compendium.
