### ISSUE TITLE
Game doesn't boot since Luma update

### ISSUE THREAD

**Issue by Gyrospiral** [DeathChaos25/PQ2_MC_Name_Patch#4]
Ever since I updated to Luma3DS 10, game doesn't boot with patch. It worked prior to this, and both v1.1 and the mod.cpk version (with the lip-sync fix mod.cpk installed) don't work. A Pokémon Ultra Sun romhack does work and Persona Q2 does work with patching disabled. The crash dump is attached in the zip
[crash_dump_00000003.zip](https://github.com/DeathChaos25/PQ2_MC_Name_Patch/files/3375981/crash_dump_00000003.zip)

**Comment by DeathChaos25** [comment]
A quick peek at your crash dump says there is an issue loading the exheader, meaning this is most likely the fault of the new luma update, and they might have changed something about exheader reading which is now causing issues, 99% of the romhacks will be unaffected by this, because the only reason you would need to mess with the exheader is when you need to add new code to the game (which is what these patches do), I will see if there is anything I can do to resolve this before opening an issue about this in the luma3ds repo.

**Comment by AmuroRayMan** [comment]
Just wanna pipe in that I just got around to updating my JP 3DS XL, updated Luma to 10.0.1 and I was attempting to use the custom names version and it crashed. Disabled Luma's game patching and the game boots. I'm gonna assume it is as you say, that Luma is breaking the patch.

**Comment by DeathChaos25** [comment]
This patch works on a rebuilt CIA, it also works on Citra no problem, so the issue here is Luma 10.0.0/1 breaking exheader patches.

**Comment by DeathChaos25** [comment]
This will be fixed in the next Luma3DS update it seems, in the meantime, [here is a build of current Luma that should fix this until next update](https://github.com/leoetlino/Luma3DS/releases/tag/v10.0.1-bps.3).
